@ cdecl ADL_Main_Control_Create(ptr long)
@ cdecl ADL_Main_Control_Destroy()
@ cdecl ADL_Adapter_NumberOfAdapters_Get(ptr)
@ cdecl ADL_Adapter_AdapterInfo_Get(ptr long)
@ cdecl ADL_Graphics_Versions_Get(ptr)
@ cdecl ADL_Graphics_VersionsX2_Get(ptr)
@ cdecl ADL2_Main_Control_Create(ptr long ptr)
@ cdecl ADL2_Main_Control_Destroy(ptr)
@ cdecl ADL2_Adapter_NumberOfAdapters_Get(ptr ptr)
@ cdecl ADL2_Adapter_AdapterInfo_Get(ptr ptr long)
@ cdecl ADL2_Adapter_AdapterInfoX2_Get(ptr ptr)
@ cdecl ADL2_Adapter_AdapterInfoX4_Get(ptr long ptr ptr)
@ cdecl ADL2_Adapter_MemoryInfo_Get(ptr long ptr)
@ cdecl ADL2_Adapter_MemoryInfo2_Get(ptr long ptr)
@ cdecl ADL2_Adapter_Graphic_Core_Info_Get(ptr long ptr)
@ cdecl ADL2_GcnAsicInfo_Get(ptr long ptr)
@ cdecl ADL2_Adapter_ASICFamilyType_Get(ptr long ptr ptr)
@ cdecl ADL_Adapter_ObservedGameClockInfo_Get(ptr long ptr ptr ptr ptr)
@ cdecl ADL2_Overdrive_Caps(ptr long ptr ptr ptr)
@ cdecl ADL2_Overdrive6_Capabilities_Get(ptr long ptr)
@ cdecl ADL2_Overdrive6_StateInfo_Get(ptr long long ptr)
@ cdecl ADL2_OverdriveN_Capabilities_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_SystemClocks_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_MemoryClocks_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_PowerLimit_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_CapabilitiesX2_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_SystemClocksX2_Get(ptr long ptr)
@ cdecl ADL2_OverdriveN_MemoryClocksX2_Get(ptr long ptr)
@ cdecl ADL2_Overdrive8_Init_Setting_Get(ptr long ptr)
@ cdecl ADL2_Graphics_Versions_Get(ptr ptr)
@ cdecl ADL2_Graphics_VersionsX2_Get(ptr ptr)
@ cdecl ADL2_Display_DisplayMapConfig_Get(ptr long ptr ptr ptr ptr long)
@ cdecl ADL2_Display_SLSMapIndex_Get(ptr long long ptr ptr)
@ cdecl ADL2_Display_SLSMapConfig_Get(ptr long long ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr long)
@ cdecl ADL2_Display_Modes_Get(ptr long long ptr ptr)
@ cdecl ADL2_Display_SourceContentAttribute_Get(ptr long long ptr)
@ cdecl ADL2_Display_SourceContentAttribute_Set(ptr long long ptr)
@ cdecl ADL2_Display_DDCInfo2_Get(ptr long long ptr)
@ cdecl ADL2_Display_DisplayInfo_Get(ptr long ptr ptr long)
@ cdecl ADL2_Display_FreeSync_Cap(ptr long long ptr)
