/*
 * SLTG typelib parser test data
 *
 * Copyright 2026 Jungwuk Ryu
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#pragma makedep ident
#pragma makedep typelib

[
    uuid(12345678-1234-1234-1234-123456789abc),
    version(1.0),
    id(5)
]
library sltg_array_test
{
    typedef struct array_struct
    {
        int values[4];
    } array_struct;
}
