@ stdcall -private wine_appx_validate_archive_path(ptr long long ptr ptr)
@ stdcall -private wine_appx_archive_open(ptr ptr long ptr)
@ stdcall -private wine_appx_archive_open_ex(ptr ptr long ptr ptr)
@ stdcall -private wine_appx_archive_close(ptr)
@ stdcall -private wine_appx_archive_get_count(ptr ptr)
@ stdcall -private wine_appx_archive_get_total_uncompressed_size(ptr ptr)
@ stdcall -private wine_appx_archive_find_entry(ptr wstr ptr)
@ stdcall -private wine_appx_archive_get_entry(ptr long ptr ptr ptr)
@ stdcall -private wine_appx_archive_stream_open(ptr long ptr)
@ stdcall -private wine_appx_archive_stream_read(ptr ptr long ptr)
@ stdcall -private wine_appx_archive_stream_cancel(ptr)
@ stdcall -private wine_appx_archive_stream_close(ptr)
@ stdcall -private appx_manifest_parse(ptr long ptr)
@ stdcall -private appx_manifest_free(ptr)
@ stdcall -private appx_manifest_get_identity(ptr)
@ stdcall -private appx_manifest_is_supported(ptr)
@ stdcall -private appx_manifest_is_framework(ptr)
@ stdcall -private appx_manifest_is_resource_package(ptr)
@ stdcall -private appx_manifest_has_run_full_trust(ptr)
@ stdcall -private appx_manifest_has_loader_search_path_override(ptr)
@ stdcall -private appx_manifest_get_loader_search_path_count(ptr)
@ stdcall -private appx_manifest_get_loader_search_path(ptr long)
@ stdcall -private appx_manifest_get_application_count(ptr)
@ stdcall -private appx_manifest_get_application(ptr long)
@ stdcall -private appx_manifest_get_dependency_count(ptr)
@ stdcall -private appx_manifest_get_dependency(ptr long)
@ stdcall -private appx_manifest_get_target_family_count(ptr)
@ stdcall -private appx_manifest_get_target_family(ptr long)
@ stdcall -private appx_manifest_get_inproc_class_count(ptr)
@ stdcall -private appx_manifest_get_inproc_class(ptr long)
@ stdcall -private appx_manifest_get_unsupported_reason_count(ptr)
@ stdcall -private appx_manifest_get_unsupported_reason(ptr long)
@ stdcall -private appx_bundle_manifest_parse(ptr long ptr)
@ stdcall -private appx_bundle_manifest_free(ptr)
@ stdcall -private appx_bundle_manifest_get_identity(ptr)
@ stdcall -private appx_bundle_manifest_get_package_count(ptr)
@ stdcall -private appx_bundle_manifest_get_package(ptr long)
@ stdcall -private appx_bundle_manifest_select(ptr ptr ptr)
@ stdcall -private appx_package_inspect(ptr ptr long ptr)
@ stdcall -private appx_package_inspect_ex(ptr ptr long ptr ptr)
@ stdcall -private appx_package_inspection_free(ptr)
@ stdcall -private appx_package_inspection_get_manifest(ptr)
@ stdcall -private appx_package_inspection_get_file_count(ptr)
@ stdcall -private appx_package_inspection_get_file(ptr long)
@ stdcall -private -ret64 appx_package_inspection_get_expanded_size(ptr)
@ stdcall -private -ret64 appx_package_inspection_get_archive_expanded_size(ptr)
@ stdcall -private appx_package_inspection_get_content_id(ptr ptr long)
@ stdcall -private appx_package_inspection_get_signer_id(ptr ptr long)
@ stdcall -private appx_package_inspection_open_stream(ptr long ptr)
@ stdcall -private appx_package_extract(ptr ptr ptr)
@ stdcall -private appx_package_extract_with_test_source(ptr ptr ptr ptr ptr)
@ stdcall -private appx_block_map_parse(ptr long ptr)
@ stdcall -private appx_block_map_free(ptr)
@ stdcall -private appx_block_map_get_file_count(ptr)
@ stdcall -private appx_block_map_get_block_count(ptr)
@ stdcall -private appx_block_map_get_file(ptr long)
@ stdcall -private appx_block_map_get_block(ptr long long)
@ stdcall -private appx_catalog_snapshot_create(int64 ptr long ptr)
@ stdcall -private appx_catalog_snapshot_deep_copy(ptr ptr)
@ stdcall -private appx_catalog_snapshot_free(ptr)
@ stdcall -private -ret64 appx_catalog_snapshot_get_epoch(ptr)
@ stdcall -private appx_catalog_snapshot_get_package_count(ptr)
@ stdcall -private appx_catalog_snapshot_get_package(ptr long)
@ stdcall -private appx_catalog_load(wstr ptr)
@ stdcall -private appx_catalog_publish(wstr int64 ptr)
@ stdcall -private appx_catalog_load_bounded(wstr long ptr ptr)
@ stdcall -private appx_catalog_publish_bounded(wstr int64 ptr long ptr)
@ stdcall -private appx_package_graph_create(ptr wstr wstr wstr long int64 ptr ptr long ptr)
@ stdcall -private appx_package_graph_create_with_classes(ptr wstr wstr wstr long int64 ptr ptr long ptr long ptr)
@ stdcall -private appx_package_graph_resolve_direct_dependencies(ptr wstr long long ptr ptr)
@ stdcall -private appx_package_graph_from_blob(ptr long ptr)
@ stdcall -private appx_package_graph_clone(ptr ptr)
@ stdcall -private appx_package_graph_validate_blob(ptr long)
@ stdcall -private appx_package_graph_free(ptr)
@ stdcall -private appx_package_graph_get_blob(ptr ptr)
@ stdcall -private -ret64 appx_package_graph_get_epoch(ptr)
@ stdcall -private -ret64 appx_package_graph_get_revision(ptr)
@ stdcall -private appx_package_graph_get_target_architecture(ptr)
@ stdcall -private appx_package_graph_get_package_count(ptr)
@ stdcall -private appx_package_graph_get_package(ptr long ptr)
@ stdcall -private appx_package_graph_get_application(ptr ptr)
@ stdcall -private appx_package_graph_lookup_basename(ptr wstr ptr)
@ stdcall -private appx_package_graph_get_inproc_class_count(ptr)
@ stdcall -private appx_package_graph_get_inproc_class(ptr long ptr)
@ stdcall -private appx_package_graph_lookup_inproc_class(ptr wstr ptr)
@ stdcall -private appx_content_types_parse(ptr long long ptr)
@ stdcall -private appx_content_types_free(ptr)
@ stdcall -private appx_content_types_get_mode(ptr)
@ stdcall -private appx_content_types_get_default_count(ptr)
@ stdcall -private appx_content_types_get_default(ptr long)
@ stdcall -private appx_content_types_get_override_count(ptr)
@ stdcall -private appx_content_types_get_override(ptr long)
@ stdcall -private appx_content_types_get_content_type(ptr wstr)
@ stdcall -private appx_signature_parse_and_verify(ptr long long ptr)
@ stdcall -private appx_signature_free(ptr)
@ stdcall -private appx_signature_get_digest_set(ptr)
@ stdcall -private appx_signature_get_signer_subject(ptr)
@ stdcall -private appx_signature_get_signer_certificate_id(ptr ptr long)
@ stdcall -private appx_signature_check_publisher(ptr wstr)
@ stdcall -private appx_signature_decode_digest_set(ptr long ptr)
@ stdcall -private appx_signature_decode_indirect_data(ptr long ptr)
@ stdcall -private appx_signature_decode_indirect_data_ex(ptr long long ptr)
@ stdcall -private appx_signature_validate_leaf_extensions(ptr long long)
@ stdcall -private appx_signature_select_ess_attribute(long long ptr)
@ stdcall -private appx_signature_validate_ess_certificate(ptr long long ptr long)
@ stdcall -private appx_signature_get_chain_policy(long long long ptr ptr)
@ stdcall -private appx_signature_evaluate_chain_status(long long long long)
@ stdcall -private appx_signature_verify_digest_set(ptr ptr)
@ stdcall -private appx_signature_compare_digest_sets(ptr ptr)
@ stdcall -private appx_archive_calculate_digest_set(ptr ptr)
@ stdcall -private appx_archive_calculate_digest_set_ex(ptr ptr ptr)
@ stdcall -private appx_bundle_inspect(ptr ptr long ptr ptr)
@ stdcall -private appx_bundle_inspect_ex(ptr ptr long ptr ptr ptr)
@ stdcall -private appx_bundle_inspection_free(ptr)
@ stdcall -private appx_bundle_inspection_get_manifest(ptr)
@ stdcall -private appx_bundle_inspection_get_selection(ptr)
@ stdcall -private appx_bundle_inspection_get_selected_package(ptr)
@ stdcall -private appx_bundle_inspection_get_signer_id(ptr ptr long)
@ stdcall -private appx_bundle_validate_with_test_source(ptr ptr ptr ptr ptr)
@ stdcall -private appx_bundle_materialize_with_test_source(int64 ptr)
@ stdcall -private appx_deployment_initialize(ptr ptr)
@ stdcall -private appx_deployment_install(ptr ptr ptr)
@ stdcall -private appx_deployment_update(ptr ptr ptr)
@ stdcall -private appx_deployment_remove(wstr ptr ptr)
@ stdcall -private appx_deployment_query(wstr ptr ptr)
@ stdcall -private appx_deployment_record_load(ptr ptr ptr)
@ stdcall -private appx_deployment_record_free(ptr)
@ stdcall -private appx_deployment_record_get_loader_file_count(ptr)
@ stdcall -private appx_deployment_record_get_loader_file(ptr long)
@ stdcall -private appx_deployment_record_get_inproc_class_count(ptr)
@ stdcall -private appx_deployment_record_get_inproc_class(ptr long)
@ stdcall -private appx_deployment_record_get_application_file_count(ptr)
@ stdcall -private appx_deployment_record_get_application_file(ptr long)
@ stdcall -private appx_deployment_record_has_loader_search_path_override(ptr)
@ stdcall -private appx_deployment_record_get_loader_search_path_count(ptr)
@ stdcall -private appx_deployment_record_get_loader_search_path(ptr long)
@ stdcall -private appx_deployment_runtime_acquire(wstr wstr ptr ptr)
@ stdcall -private appx_deployment_runtime_free(ptr)
@ stdcall -private appx_deployment_runtime_get_graph(ptr)
@ stdcall -private appx_deployment_runtime_get_lease_count(ptr)
@ stdcall -private appx_deployment_runtime_get_leases(ptr)
@ stdcall -private appx_deployment_runtime_get_attach(ptr)
@ stdcall -private appx_deployment_runtime_get_executable_handle(ptr)
@ stdcall -private appx_deployment_runtime_get_executable_path(ptr)
@ stdcall -private appx_deployment_runtime_get_parameters(ptr)
@ stdcall -private appx_deployment_runtime_get_current_directory(ptr)
@ stdcall -private appx_deployment_launch(wstr wstr ptr ptr ptr)
@ stdcall -private appx_deployment_recover(ptr ptr)
@ stdcall -private appx_deployment_collect_garbage(ptr ptr)
@ stdcall -private appx_deployment_result_free(ptr)
@ stdcall -private appx_deployment_result_get_flags(ptr)
@ stdcall -private -ret64 appx_deployment_result_get_catalog_epoch(ptr)
@ stdcall -private -ret64 appx_deployment_result_get_reclaimed_bytes(ptr)
@ stdcall -private appx_deployment_result_get_reclaimed_entries(ptr)
@ stdcall -private appx_deployment_result_get_package_full_name(ptr ptr ptr)
@ stdcall -private wine_appx_get_package_path_by_full_name(wstr ptr ptr)
@ stdcall -private wine_appx_get_packages_by_family(wstr ptr ptr ptr ptr)
@ stdcall -private wine_appx_get_package_publisher_by_full_name(wstr ptr ptr)
